'\" t
.\"     Title: uri_absolute
.\"    Author: Mo McRoberts
.\" Generator: DocBook XSL Stylesheets v1.77.1 <http://docbook.sf.net/>
.\"      Date: 02/09/2013
.\"    Manual: URI Functions
.\"    Source: System Programmer's Manual
.\"  Language: English
.\"
.TH "URI_ABSOLUTE" "3" "02/09/2013" "System Programmer's Manual" "URI Functions"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
uri_absolute \- determine whether a URI is relative or absolute
.SH "LIBRARY"
.PP
URI parsing library (liburi, \-luri)
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <liburi\&.h>
.fi
.ft
.HP \w'int\ uri_absolute('u
.BI "int uri_absolute(URI\ *" "uri" ");"
.SH "DESCRIPTION"
.PP
The
\fBuri_absolute\fR
function determines whether a parsed URI is absolute or relative\&.
.PP
An absolute URI is one which does not require the use of a base URI in order to be used\&.
.SH "PARAMETERS"
.PP
\fIuri\fR
.RS 4
The URI to evaluate\&.
.RE
.SH "RETURN VALUE"
.PP
If successful,
\fBuri_absolute\fR
returns
1
if
\fIuri\fR
contains an absolute URI, and
0
otherwise\&.
.PP
If an error occurs,
\fBuri_absolute\fR
returns
\-1, and sets
\fIerrno\fR
accordingly\&.
.SH "EXAMPLE"
.sp
.if n \{\
.RS 4
.\}
.nf
URI *relative, *absolute;
int r, a;

absolute = uri_create_str("http://example\&.com", NULL);

relative = uri_create_str("sample?toggle=1", NULL);

/* a will be set to 1 */
a = uri_absolute(absolute);

/* r will be set to 0 */
b = uri_absolute(relative);
	
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.PP

\fBliburi\fR(3),
\fBuri_absolute_path\fR(3)\&.
